name: gerrit checks

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
      gerrit-ref:
        type: string
      change:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: lineageos-infra/fetch-gerrit-change@main
      with:
        repository: ${{ github.repository }}
        gerrit-ref: ${{ inputs.gerrit-ref }}
        ref: ${{ inputs.ref }}

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Generate Android.bp
      run: |
        ./gradlew app:generateBp
        if [[ ! -z $(git status -s) ]]; then
          git status
          exit -1
        fi

    - uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
